CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS flight_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    flight_number VARCHAR(255),
    origin VARCHAR(255),
    destination VARCHAR(255),
    departure_time VARCHAR(255),
    arrival_time VARCHAR(255),
    PRIMARY KEY (id)
);

ALTER TABLE flight_model ALTER COLUMN arrival_time TYPE timestamp(6) without time zone USING arrival_time::timestamp(6) without time zone;
ALTER TABLE flight_model ALTER COLUMN departure_time TYPE timestamp(6) without time zone USING departure_time::timestamp(6) without time zone;

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL001', 'New York', 'Los Angeles', '2023-10-01 08:00', '2023-10-01 11:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL001');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL002', 'Chicago', 'Miami', '2023-10-01 09:00', '2023-10-01 12:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL002');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL003', 'Dallas', 'San Francisco', '2023-10-01 10:00', '2023-10-01 13:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL003');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL004', 'Houston', 'Seattle', '2023-10-01 11:00', '2023-10-01 14:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL004');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL005', 'Boston', 'Denver', '2023-10-01 12:00', '2023-10-01 15:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL005');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL006', 'Atlanta', 'Las Vegas', '2023-10-01 13:00', '2023-10-01 16:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL006');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL007', 'Philadelphia', 'Phoenix', '2023-10-01 14:00', '2023-10-01 17:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL007');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL008', 'San Antonio', 'San Diego', '2023-10-01 15:00', '2023-10-01 18:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL008');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL009', 'San Jose', 'Orlando', '2023-10-01 16:00', '2023-10-01 19:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL009');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL010', 'Austin', 'Charlotte', '2023-10-01 17:00', '2023-10-01 20:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL010');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL011', 'Jacksonville', 'Detroit', '2023-10-01 18:00', '2023-10-01 21:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL011');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL012', 'Columbus', 'Memphis', '2023-10-01 19:00', '2023-10-01 22:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL012');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL013', 'Fort Worth', 'Baltimore', '2023-10-01 20:00', '2023-10-01 23:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL013');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL014', 'Indianapolis', 'Milwaukee', '2023-10-01 21:00', '2023-10-02 00:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL014');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL015', 'Charlotte', 'Albuquerque', '2023-10-01 22:00', '2023-10-02 01:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL015');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL016', 'San Francisco', 'Tucson', '2023-10-01 23:00', '2023-10-02 02:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL016');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL017', 'Seattle', 'Fresno', '2023-10-02 00:00', '2023-10-02 03:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL017');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL018', 'Denver', 'Sacramento', '2023-10-02 01:00', '2023-10-02 04:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL018');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL019', 'Washington', 'Kansas City', '2023-10-02 02:00', '2023-10-02 05:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL019');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL020', 'Nashville', 'Mesa', '2023-10-02 03:00', '2023-10-02 06:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL020');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL021', 'Oklahoma City', 'Atlanta', '2023-10-02 04:00', '2023-10-02 07:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL021');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL022', 'El Paso', 'Omaha', '2023-10-02 05:00', '2023-10-02 08:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL022');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL023', 'Portland', 'Raleigh', '2023-10-02 06:00', '2023-10-02 09:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL023');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL024', 'Las Vegas', 'Miami', '2023-10-02 07:00', '2023-10-02 10:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL024');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL025', 'Detroit', 'Long Beach', '2023-10-02 08:00', '2023-10-02 11:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL025');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL026', 'Memphis', 'Virginia Beach', '2023-10-02 09:00', '2023-10-02 12:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL026');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL027', 'Louisville', 'Oakland', '2023-10-02 10:00', '2023-10-02 13:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL027');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL028', 'Baltimore', 'Minneapolis', '2023-10-02 11:00', '2023-10-02 14:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL028');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL029', 'Milwaukee', 'Tulsa', '2023-10-02 12:00', '2023-10-02 15:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL029');

INSERT INTO flight_model (flight_number, origin, destination, departure_time, arrival_time)
SELECT 'FL030', 'Albuquerque', 'Arlington', '2023-10-02 13:00', '2023-10-02 16:00'
WHERE NOT EXISTS (SELECT 1 FROM flight_model WHERE flight_number = 'FL030');